import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <header className="sticky top-0 z-30 bg-white/70 backdrop-blur dark:bg-neutral-950/70">
          <div className="mx-auto max-w-4xl px-6 py-4 flex items-center justify-between">
            <a href="/" className="font-semibold tracking-tight">shreyas.dev</a>
            <nav className="flex items-center gap-4 text-sm">
              <a href="/" className="opacity-80 hover:opacity-100">Home</a>
              <a href="/musings" className="opacity-80 hover:opacity-100">Musings</a>
              <a href="/#about" className="opacity-80 hover:opacity-100">About</a>
              <a href="/#contact" className="opacity-80 hover:opacity-100">Contact</a>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
